### ISSUE TITLE
Try out and investigate running Vaadin Portlets on Liferay DXP 7.2

### ISSUE THREAD

**Issue by pleku** [vaadin/portlet#147]
Prerequisite for vaadin/flow#5815.

https://www.liferay.com/downloads-community

According to e.g. https://portal.liferay.dev/docs/7-2/appdev
> Portlet 3.0 or 2.0 compliant portlets deploy on Liferay Portal.

So we should spend two days (third if results merit) in trying and investigating if/how we can get a Vaadin portlet up and running there.

**Comment by caalador** [comment]
Portlets for Liferay require bringing in `VaadinLiferayRequest` and `VaadinHttpAndPortletRequest` from V7/V8.

`PortletMethods.js` needs to be modified to not use < or && as Liferay parses the head response content as xml and the < fails the parsing as a faulty start tag.

At the moment liferay doesn't populate some objects on the client that are required for using the portletHub which we populate for them in the poc. 

There changes are in the feature/liferay branch in portlet

The addressbook demo only requires change to the external stats url.

This change is in the feature/liferay branch in addressbook-portlet
 
**To run vaadin 14 portlets in Liferay 7.2.1-ga2**

- Unpack of the vaadin-portlet-static.war and copy of `VAADIN/*` to `liferay-ce-portal-7.2.1-ga2/tomcat-9.0.17/webapps/ROOT/html`
- Unpack flow-client.jar and copy `VAADIN/static` to `liferay-ce-portal-7.2.1-ga2/tomcat-9.0.17/webapps/ROOT/html`
- Add parameter `-Dvaadin.portlet.static.resources.mapping=/html/` to setenv.[bat|sh]  in `liferay-ce-portal-7.2.1-ga2/tomcat-9.0.17/bin`
- Copy portlet.war files to  `liferay-ce-portal-7.2.1-ga2/deploy`
- Start tomcat server
- Add portlets using Add -> Widgets -> Undefined
  - to define portlet package create liferay-portlet.xml with needed information.

The unanswered question is that how should the portlet get registered on the client so that we wouldn't need to populate liferay specific data on the client to get js features to work for portlet3.0.

**Comment by caalador** [comment]
Made a question to the Liferay forums
https://liferay.dev/forums/-/message_boards/message/118059099
